import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  centerBox: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    maxWidth: 400,
    width: "100%",
    alignSelf: "center",
    paddingVertical: 40,
  },
  headerSection: {
    alignItems: "center",
    width: "100%",
    marginBottom: 30,
  },
  logo: {
    width: width * 0.8,
    height: 160,
    marginBottom: 10,
  },
  title: {
    color: "#111827",
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 8,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  subtitle: {
    color: "#6b7280",
    fontSize: 16,
    textAlign: "center",
    lineHeight: 22,
    fontWeight: "400",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#111827",
    width: "100%",
    shadowColor: "#111827",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    marginBottom: 20,
  },
  cardHeader: {
    borderBottomWidth: 2,
    borderBottomColor: "#111827",
    paddingVertical: 18,
    paddingHorizontal: 20,
    backgroundColor: "#f9fafb",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  cardTitle: {
    color: "#111827",
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  pickerContainer: {
    padding: 20,
  },
  pickerLabel: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 12,
    letterSpacing: -0.3,
  },
  pickerBox: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderColor: "#111827",
    borderWidth: 2,
    overflow: "hidden",
  },
  picker: {
    height: 56,
    color: "#111827",
  },
  roleDescription: {
    backgroundColor: "#f8f9fa",
    padding: 16,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: "#afd826",
  },
  roleDescriptionText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 20,
  },
  errorContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  error: {
    color: "#ef4444",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    backgroundColor: "#fef2f2",
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  actionSection: {
    width: "100%",
    alignItems: "center",
  },
  submitBtn: {
    backgroundColor: "#afd826",
    paddingVertical: 18,
    borderRadius: 12,
    alignItems: "center",
    width: "100%",
    shadowColor: "#afd826",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    marginBottom: 16,
  },
  submitBtnDisabled: {
    backgroundColor: "#9ca3af",
    shadowOpacity: 0,
    elevation: 0,
  },
  submitText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 17,
    letterSpacing: 0.3,
  },
  helpText: {
    color: "#6b7280",
    fontSize: 14,
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 18,
  },
});