openapi: 3.0.0
info:
  title: Transporter Dashboard API
  version: 1.0.0
paths:
  /api/dashboard/stats:
    get:
      summary: Get today's stats
      responses:
        '200':
          description: Stats retrieved successfully
  /api/dashboard/manager:
    get:
      summary: Get manager profile
      responses:
        '200':
          description: Manager info retrieved
